[package]
name = "proa"
version = "0.1.0"
edition = "2021"

# TODO Clean up dependency versions.
[dependencies]
anyhow = "1.0.71"
futures = "0.3.28"
gethostname = "0.4.2"
k8s-openapi = { version = "0.18.0", features = ["v1_26"] }
kube = { version = "0.82.2", features = ["client", "runtime"] }
pin-project = "1.1.0"
tokio = { version = "1.28.1", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
