apiVersion: batch/v1
kind: Job
metadata:
  name: proa
spec:
  template:
    spec:
      containers:
      - name: main
        image: proa
        command:
        - proa
        - echo
        - "It worked."
      - name: nginx
        image: nginx
        command:
        - sh
        - -cex
        - |
          sleep 30
          exec /docker-entrypoint.sh nginx -g "daemon off;"
        readinessProbe:
          httpGet:
            port: 80
      restartPolicy: Never
      serviceAccountName: proa
      shareProcessNamespace: true

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: proa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proa
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proa
subjects:
- kind: ServiceAccount
  name: proa
roleRef:
  kind: Role
  name: proa
  apiGroup: rbac.authorization.k8s.io
