# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: proa
# spec:
#   template:
#     spec:
#       containers:
#       - name: main
#         image: proa
#         command:
#         - proa
#         - echo
#         - "It worked."
#       restartPolicy: Never
#       serviceAccountName: proa

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: proa
spec:
  selector:
    matchLabels:
      app: proa
  template:
    metadata:
      labels:
        app: proa
    spec:
      containers:
      - name: main
        image: proa
        args:
        - sleep
        - "60"
        env:
        - name: RUST_LOG
          value: proa=debug
      - name: nginx
        image: nginx
        command:
        - sh
        - -cex
        - |
          sleep 30
          exec /docker-entrypoint.sh nginx -g "daemon off;"
        readinessProbe:
          httpGet:
            port: 80
      serviceAccountName: proa
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 5

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: proa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proa
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proa
subjects:
- kind: ServiceAccount
  name: proa
roleRef:
  kind: Role
  name: proa
  apiGroup: rbac.authorization.k8s.io
